<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!--Because an application's API isn't typically referenced from outside the assembly, types can be made internal -->
    <NoWarn>CA1515</NoWarn>
    <TargetFramework>net10.0</TargetFramework>
    <RollForward>major</RollForward>
    <AssemblyName>IceRpc.SlicecGen</AssemblyName>
    <!-- We don't generate a NuGet package for IceRpc.SlicecGen. The generator is packaged with IceRpc.Slice.Tools -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../ZeroC.CodeBuilder/*.cs" />
    <PackageReference Include="dunet" Version="1.11.3" />
    <ProjectReference Include="../ZeroC.Slice.Codec/ZeroC.Slice.Codec.csproj" />
  </ItemGroup>
</Project>
